backend:
  name: git-gateway
  branch: main
  repo: d-rafi/psych2 
local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string", default: "Welcome" }
          - { name: "body", label: "Content", widget: "markdown" }
