backend:
  name: github
  repo: d-rafi/psychmind-pro
media_folder: "images/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }
