backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Content", widget: "markdown" }
